services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "SenhaForte123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: BaseExchange/APIBaseExchange/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BaseExchangeDb;User Id=sa;Password=SenhaForte123!;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./BaseExchangeFront
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080/api
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  sql_data:
