services:
  api:
    build:
      context: .
      dockerfile: APIBaseExchange/Dockerfile
    ports:
      - "8080:8080"
      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BaseExchangeDb;User Id=sa;Password=SenhaForte123!;TrustServerCertificate=True;

    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "SenhaForte123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
