FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY BaseExchange/APIBaseExchange/APIBaseExchange.csproj APIBaseExchange/
COPY BaseExchange/App/App.csproj App/
COPY BaseExchange/Domain/Domain.csproj Domain/
COPY BaseExchange/Infra/Infra.csproj Infra/

RUN dotnet restore APIBaseExchange/APIBaseExchange.csproj

COPY .. .
WORKDIR /src/BaseExchange/APIBaseExchange
RUN dotnet build APIBaseExchange.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish APIBaseExchange.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "APIBaseExchange.dll"]
