FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY *.sln ./
COPY APIBaseExchange/*.csproj ./APIBaseExchange/
COPY Application/*.csproj ./Application/
COPY Domain/*.csproj ./Domain/
COPY Infra/*.csproj ./Infra/

RUN dotnet restore

COPY . .
WORKDIR /app/APIBaseExchange
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/APIBaseExchange/out .

ENTRYPOINT ["dotnet", "APIBaseExchange.dll"]
