// <auto-generated />
using System;
using Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.ExposicaoFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ExposicaoFinanceira");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = "PETR4",
                            AtualizadoEm = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = 0m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = "VALE3",
                            AtualizadoEm = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = 0m
                        },
                        new
                        {
                            Id = 3,
                            Ativo = "VIIA4",
                            AtualizadoEm = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Valor = 0m
                        });
                });

            modelBuilder.Entity("Domain.Models.Ordem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aceita")
                        .HasColumnType("bit");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lado")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ordem");
                });
#pragma warning restore 612, 618
        }
    }
}
